# Generated by Django 5.1 on 2024-10-13 18:06

import django.core.serializers.json
import django.db.models.deletion
import django.db.models.functions.text
import django.db.models.manager
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('first_name', models.CharField(max_length=35)),
                ('last_name', models.CharField(max_length=40)),
                ('email', models.EmailField(db_index=True, max_length=55)),
                ('title', models.CharField(max_length=75)),
                ('comment', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_name', models.TextField()),
                ('processed', models.BooleanField(default=False)),
                ('processing_error', models.TextField(default='')),
                ('body', models.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('verified', models.BooleanField(default=False)),
                ('first_name', models.CharField(default='', max_length=50)),
                ('last_name', models.CharField(default='', max_length=50)),
                ('birth_date', models.DateField(null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(to='auth.group')),
                ('user_permissions', models.ManyToManyField(to='auth.permission')),
            ],
            managers=[
                ('people', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Geofield',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('feature_id', models.TextField()),
                ('unique_id', models.GeneratedField(db_persist=True, expression=django.db.models.functions.text.Concat('user', models.Value(','), 'feature_id', output_field=models.TextField()), output_field=models.TextField(), unique=True, verbose_name='Unique Feature ID')),
                ('geometry', models.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PhoneNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('verified', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product_id', models.IntegerField()),
                ('product_name', models.TextField(default='')),
                ('variant_id', models.IntegerField(unique=True)),
                ('name', models.TextField()),
                ('description', models.TextField(default='')),
                ('price', models.TextField()),
                ('is_usage_based', models.BooleanField(default=False)),
                ('interval', models.TextField(default='')),
                ('interval_count', models.IntegerField(null=True)),
                ('trial_interval', models.TextField(default='')),
                ('trial_interval_count', models.IntegerField(null=True)),
                ('sort', models.IntegerField(null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['variant_id', 'name'], name='analysis_pl_variant_a1e9c6_idx'), models.Index(fields=['variant_id'], name='analysis_pl_variant_2ba758_idx')],
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('file', models.FileField(upload_to='pdfs')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lemonsqueezy_id', models.TextField(unique=True)),
                ('order_id', models.IntegerField()),
                ('name', models.TextField(default='')),
                ('email', models.EmailField(max_length=254, verbose_name='email address')),
                ('status', models.TextField()),
                ('status_formatted', models.TextField()),
                ('renews_at', models.TextField(default='')),
                ('ends_at', models.TextField(default='')),
                ('trial_ends_at', models.TextField(default='')),
                ('price', models.TextField()),
                ('is_usage_based', models.BooleanField(default=False)),
                ('is_paused', models.BooleanField(default=False)),
                ('subscription_item_id', models.IntegerField()),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analysis.plan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['id', 'email'], name='analysis_us_id_aa5374_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(condition=models.Q(('verified', True)), fields=['email'], name='unique_verified_email'),
        ),
        migrations.AddIndex(
            model_name='phonenumber',
            index=models.Index(fields=['number', 'user'], name='analysis_ph_number_2baf92_idx'),
        ),
        migrations.AddIndex(
            model_name='phonenumber',
            index=models.Index(condition=models.Q(('verified', True)), fields=['number'], name='verified_number'),
        ),
        migrations.AddConstraint(
            model_name='phonenumber',
            constraint=models.UniqueConstraint(condition=models.Q(('verified', True)), fields=('number', 'user'), name='unique_verfified_number'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['id'], name='analysis_re_id_d2677a_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['file'], name='analysis_re_file_0ac1d0_idx'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['lemonsqueezy_id'], name='analysis_su_lemonsq_c91dcc_idx'),
        ),
    ]
