# Generated by Django 5.0.6 on 2024-07-01 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geofield',
            name='feature_id',
            field=models.UUIDField(null=True, unique=True),
        ),
    ]
