# Generated by Django 5.0.6 on 2024-07-16 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0002_alter_geofield_feature_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('first_name', models.CharField(max_length=35)),
                ('last_name', models.CharField(max_length=40)),
                ('email', models.EmailField(db_index=True, max_length=55)),
                ('title', models.CharField(max_length=75)),
                ('comment', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
