# Generated by Django 5.0.6 on 2024-08-01 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0003_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product_id', models.IntegerField()),
                ('product_name', models.TextField(null=True)),
                ('variant_id', models.IntegerField(unique=True)),
                ('name', models.TextField()),
                ('description', models.TextField(null=True)),
                ('price', models.TextField()),
                ('is_usage_based', models.BooleanField(default=False)),
                ('interval', models.TextField(null=True)),
                ('interval_count', models.IntegerField(null=True)),
                ('trial_interval', models.TextField(null=True)),
                ('trial_interval_count', models.IntegerField(null=True)),
                ('sort', models.IntegerField(null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['variant_id', 'name'], name='analysis_pl_variant_a1e9c6_idx'), models.Index(fields=['variant_id'], name='analysis_pl_variant_2ba758_idx')],
            },
        ),
    ]
