# Generated by Django 5.1 on 2024-08-28 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0003_webhookevent_alter_plan_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='webhookevent',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='webhookevent',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
