# Generated by Django 5.1 on 2024-09-04 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0005_alter_subscription_ends_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='webhookevent',
            old_name='proccessed',
            new_name='processed',
        ),
        migrations.RenameField(
            model_name='webhookevent',
            old_name='proccessing_error',
            new_name='processing_error',
        ),
    ]
